### ISSUE TITLE
How to overwrite css styles of the editor?

### ISSUE THREAD

**Issue by bahodir-annaev** [mycurelabs/vue-wysiwyg#9]
I'm using vue-wysiwyg in a .js file component (not a .vue). How can I overwrite default styles of the editor? Demo uses vuetify to accomplish this. Is there a different way?

**Comment by jofftiquez** [comment]
You can either override the styles from here https://github.com/mycurelabs/vue-wysiwyg/blob/196e876efcb4f159fe7fab02292197644b7270a2/src/McWysiwyg.vue#L320 or you can create global styles for now. I will consider adding an option for custom styles.

**Comment by jofftiquez** [comment]
See #10
